name: imgix_flutter_example
description: imgix_flutter example
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-6.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  imgix_flutter:
    path: ..

flutter:
  uses-material-design: true
