name: imgix_flutter
description: An Imgix Flutter wrapper to embed Imgix URLs with options easily
version: 0.3.0
homepage: https://github.com/Cretezy/imgix_flutter.dart

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  imgix: ^0.3.0
dev_dependencies:
  flutter_lints: ^2.0.1
